<?php
 /**
  * Title: Front Page
  * Slug: alpha-digital-agency/front-page
  * Categories: alpha-digital-agency
  */
?>

<!-- wp:spacer {"height":"50px","className":"heightss","style":{"spacing":{"margin":{"top":"0","bottom":"0"}}}} -->
<div style="margin-top:0;margin-bottom:0;height:50px" aria-hidden="true" class="wp-block-spacer heightss"></div>
<!-- /wp:spacer -->

<!-- wp:group {"className":"banner-area","style":{"spacing":{"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"constrained","contentSize":"80%"}} -->
<div class="wp-block-group banner-area" style="margin-top:0;margin-bottom:0"><!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:heading {"style":{"typography":{"fontSize":"38px"}},"fontFamily":"cormorant"} -->
<h2 class="wp-block-heading header-h has-cormorant-font-family" style="font-size:38px"><span class="color-element"><?php esc_html_e('Generate Your Traffic ','alpha-digital-agency'); ?></span><?php esc_html_e('Boost Your','alpha-digital-agency'); ?><br><?php esc_html_e('Site Today!!','alpha-digital-agency'); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"medium","fontFamily":"inter"} -->
<p class="header-p has-inter-font-family has-medium-font-size"><?php esc_html_e('Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.','alpha-digital-agency'); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"primary","textColor":"background","style":{"typography":{"fontStyle":"normal","fontWeight":"600"},"elements":{"link":{"color":{"text":"var:preset|color|background"}}}},"fontFamily":"inter"} -->
<div class="wp-block-button has-inter-font-family" style="font-style:normal;font-weight:600"><a class="wp-block-button__link has-background-color has-primary-background-color has-text-color has-background has-link-color wp-element-button"><?php esc_html_e('Signup Today','alpha-digital-agency'); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","className":"image-area-wrap"} -->
<div class="wp-block-column is-vertically-aligned-center image-area-wrap"><!-- wp:image {"id":8,"sizeSlug":"full","linkDestination":"none","className":"design-small"} -->
<figure class="wp-block-image size-full design-small"><img src="<?php echo get_parent_theme_file_uri( '/images/design-small.png' ); ?>" alt="" class="wp-image-8"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":31,"sizeSlug":"full","linkDestination":"none","align":"center"} -->
<figure class="wp-block-image aligncenter size-full"><img src="<?php echo get_parent_theme_file_uri( '/images/banner-image.png' ); ?>" alt="" class="wp-image-31"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":6,"sizeSlug":"full","linkDestination":"none","className":"design-big"} -->
<figure class="wp-block-image size-full design-big"><img src="<?php echo get_parent_theme_file_uri( '/images/design-big.png' ); ?>" alt="" class="wp-image-6"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":"50px","className":"heightss","style":{"spacing":{"margin":{"top":"0","bottom":"0"}}}} -->
<div style="margin-top:0;margin-bottom:0;height:50px" aria-hidden="true" class="wp-block-spacer heightss"></div>
<!-- /wp:spacer -->

<!-- wp:group {"className":"choose-us-aera","style":{"color":{"background":"var(--wp--preset--color--secondary-theme)"},"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60","left":"0","right":"0"}}},"layout":{"type":"constrained","contentSize":"80%"}} -->
<div class="wp-block-group choose-us-aera has-background" style="background-color:var(--wp--preset--color--secondary-theme);padding-top:var(--wp--preset--spacing--60);padding-right:0;padding-bottom:var(--wp--preset--spacing--60);padding-left:0"><!-- wp:image {"id":8,"sizeSlug":"full","linkDestination":"none","className":"design-2-small"} -->
<figure class="wp-block-image size-full design-2-small"><img src="<?php echo get_parent_theme_file_uri( '/images/design-small.png' ); ?>" alt="" class="wp-image-8"/></figure>
<!-- /wp:image -->

<!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:image {"id":52,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="<?php echo get_parent_theme_file_uri( '/images/about-image.jpg' ); ?>" alt="" class="wp-image-52"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:heading {"level":3,"style":{"typography":{"fontSize":"30px"}},"fontFamily":"cormorant"} -->
<h3 class="wp-block-heading has-cormorant-font-family" style="font-size:30px"><span class="color-element"><?php esc_html_e('Why ','alpha-digital-agency'); ?></span><?php esc_html_e('Choose Us?','alpha-digital-agency'); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"normal","fontFamily":"inter"} -->
<p class="has-inter-font-family has-normal-font-size"><?php esc_html_e('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt&nbsp;ut labore et dolore.','alpha-digital-agency'); ?></p>
<!-- /wp:paragraph -->

<!-- wp:essential-blocks/progress-bar {"blockId":"eb-progressbar-c12qy","blockMeta":{"desktop":".eb-progressbar-wrapper.eb-progressbar-c12qy{margin-top:0px;margin-right:0px;margin-left:0px;margin-bottom:25px}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-line{height:12px;background-color:rgba(217,217,217,1)}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-circle{width:200px;height:200px}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-circle-inner-content{padding:12px}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-circle-half{border-width:12px;border-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-circle-fill .eb-progressbar-circle-half,.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-half-circle-fill .eb-progressbar-circle-half{background-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-line-fill{height:12px;background-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-title{color:var(\u002d\u002deb-global-heading-color)}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-count-wrap{color:var(\u002d\u002deb-global-heading-color)}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-circle-inner{border-color:rgba(217,217,217,1);border-width:12px}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-half-circle-after{width:200px;color:var(\u002d\u002deb-global-text-color)}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-half-circle{width:200px;height:calc(100 * 1px)}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-box{height:200px;width:140px;border-width:12px;border-color:rgba(217,217,217,1)}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-box-fill{background-color:var(--wp--preset--color--primary)}","tab":".eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-half-circle{height:calc(100 * 1px)}","mobile":".eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-c12qy .eb-progressbar-half-circle{height:calc(100 * 1px)}"},"title":"Web Analytics","progress":91,"progressColor":"var(--wp--preset--color--primary)","strokeColor":"rgba(217,217,217,1)","commonStyles":{"desktop":".eb-parent-eb-progressbar-c12qy{display:block}.root-eb-progressbar-c12qy{position:relative}","tab":".eb-parent-eb-progressbar-c12qy{display:block}","mobile":".eb-parent-eb-progressbar-c12qy{display:block}"}} -->
<div class="wp-block-essential-blocks-progress-bar  root-eb-progressbar-c12qy"><div class="eb-parent-wrapper eb-parent-eb-progressbar-c12qy "><div class="eb-progressbar-wrapper eb-progressbar-c12qy"><div class="eb-progressbar-line-container center"><div class="eb-progressbar-title"><?php esc_html_e('Web Analytics','alpha-digital-agency'); ?></div><div class="eb-progressbar eb-progressbar-line" data-layout="line" data-count="91" data-duration="1500"><span class="eb-progressbar-count-wrap"><span class="eb-progressbar-count"><?php esc_html_e('91','alpha-digital-agency'); ?></span><span class="postfix">%</span></span><span class="eb-progressbar-line-fill"></span></div></div></div></div></div>
<!-- /wp:essential-blocks/progress-bar -->

<!-- wp:essential-blocks/progress-bar {"blockId":"eb-progressbar-fo8wp","blockMeta":{"desktop":".eb-progressbar-wrapper.eb-progressbar-fo8wp{margin-top:0px;margin-right:0px;margin-left:0px;margin-bottom:25px}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-line{height:12px;background-color:rgba(217,217,217,1)}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-circle{width:200px;height:200px}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-circle-inner-content{padding:12px}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-circle-half{border-width:12px;border-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-circle-fill .eb-progressbar-circle-half,.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-half-circle-fill .eb-progressbar-circle-half{background-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-line-fill{height:12px;background-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-title{color:var(\u002d\u002deb-global-heading-color)}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-count-wrap{color:var(\u002d\u002deb-global-heading-color)}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-circle-inner{border-color:rgba(217,217,217,1);border-width:12px}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-half-circle-after{width:200px;color:var(\u002d\u002deb-global-text-color)}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-half-circle{width:200px;height:calc(100 * 1px)}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-box{height:200px;width:140px;border-width:12px;border-color:rgba(217,217,217,1)}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-box-fill{background-color:var(--wp--preset--color--primary)}","tab":".eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-half-circle{height:calc(100 * 1px)}","mobile":".eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-fo8wp .eb-progressbar-half-circle{height:calc(100 * 1px)}"},"title":"Creative Work","progress":80,"progressColor":"var(--wp--preset--color--primary)","strokeColor":"rgba(217,217,217,1)","commonStyles":{"desktop":".eb-parent-eb-progressbar-fo8wp{display:block}.root-eb-progressbar-fo8wp{position:relative}","tab":".eb-parent-eb-progressbar-fo8wp{display:block}","mobile":".eb-parent-eb-progressbar-fo8wp{display:block}"}} -->
<div class="wp-block-essential-blocks-progress-bar  root-eb-progressbar-fo8wp"><div class="eb-parent-wrapper eb-parent-eb-progressbar-fo8wp "><div class="eb-progressbar-wrapper eb-progressbar-fo8wp"><div class="eb-progressbar-line-container center"><div class="eb-progressbar-title"><?php esc_html_e('Creative Work','alpha-digital-agency'); ?></div><div class="eb-progressbar eb-progressbar-line" data-layout="line" data-count="80" data-duration="1500"><span class="eb-progressbar-count-wrap"><span class="eb-progressbar-count"><?php esc_html_e('80','alpha-digital-agency'); ?></span><span class="postfix">%</span></span><span class="eb-progressbar-line-fill"></span></div></div></div></div></div>
<!-- /wp:essential-blocks/progress-bar -->

<!-- wp:essential-blocks/progress-bar {"blockId":"eb-progressbar-1vzet","blockMeta":{"desktop":".eb-progressbar-wrapper.eb-progressbar-1vzet{margin-top:0px;margin-right:0px;margin-left:0px;margin-bottom:25px}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-line{height:12px;background-color:rgba(217,217,217,1)}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-circle{width:200px;height:200px}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-circle-inner-content{padding:12px}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-circle-half{border-width:12px;border-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-circle-fill .eb-progressbar-circle-half,.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-half-circle-fill .eb-progressbar-circle-half{background-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-line-fill{height:12px;background-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-title{color:var(\u002d\u002deb-global-heading-color)}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-count-wrap{color:var(\u002d\u002deb-global-heading-color)}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-circle-inner{border-color:rgba(217,217,217,1);border-width:12px}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-half-circle-after{width:200px;color:var(\u002d\u002deb-global-text-color)}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-half-circle{width:200px;height:calc(100 * 1px)}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-box{height:200px;width:140px;border-width:12px;border-color:rgba(217,217,217,1)}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-box-fill{background-color:var(--wp--preset--color--primary)}","tab":".eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-half-circle{height:calc(100 * 1px)}","mobile":".eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-1vzet .eb-progressbar-half-circle{height:calc(100 * 1px)}"},"title":"Real Content","progress":70,"progressColor":"var(--wp--preset--color--primary)","strokeColor":"rgba(217,217,217,1)","commonStyles":{"desktop":".eb-parent-eb-progressbar-1vzet{display:block}.root-eb-progressbar-1vzet{position:relative}","tab":".eb-parent-eb-progressbar-1vzet{display:block}","mobile":".eb-parent-eb-progressbar-1vzet{display:block}"}} -->
<div class="wp-block-essential-blocks-progress-bar  root-eb-progressbar-1vzet"><div class="eb-parent-wrapper eb-parent-eb-progressbar-1vzet "><div class="eb-progressbar-wrapper eb-progressbar-1vzet"><div class="eb-progressbar-line-container center"><div class="eb-progressbar-title"><?php esc_html_e('Real Content','alpha-digital-agency'); ?></div><div class="eb-progressbar eb-progressbar-line" data-layout="line" data-count="70" data-duration="1500"><span class="eb-progressbar-count-wrap"><span class="eb-progressbar-count"><?php esc_html_e('70','alpha-digital-agency'); ?></span><span class="postfix">%</span></span><span class="eb-progressbar-line-fill"></span></div></div></div></div></div>
<!-- /wp:essential-blocks/progress-bar -->

<!-- wp:essential-blocks/progress-bar {"blockId":"eb-progressbar-362ez","blockMeta":{"desktop":".eb-progressbar-wrapper.eb-progressbar-362ez{margin-top:0px;margin-right:0px;margin-left:0px;margin-bottom:25px}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-line{height:12px;background-color:rgba(217,217,217,1)}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-circle{width:200px;height:200px}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-circle-inner-content{padding:12px}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-circle-half{border-width:12px;border-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-circle-fill .eb-progressbar-circle-half,.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-half-circle-fill .eb-progressbar-circle-half{background-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-line-fill{height:12px;background-color:var(--wp--preset--color--primary)}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-title{color:var(\u002d\u002deb-global-heading-color)}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-count-wrap{color:var(\u002d\u002deb-global-heading-color)}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-circle-inner{border-color:rgba(217,217,217,1);border-width:12px}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-half-circle-after{width:200px;color:var(\u002d\u002deb-global-text-color)}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-half-circle{width:200px;height:calc(100 * 1px)}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-box{height:200px;width:140px;border-width:12px;border-color:rgba(217,217,217,1)}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-box-fill{background-color:var(--wp--preset--color--primary)}","tab":".eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-half-circle{height:calc(100 * 1px)}","mobile":".eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-circle-inner-content{padding:px}.eb-progressbar-wrapper.eb-progressbar-362ez .eb-progressbar-half-circle{height:calc(100 * 1px)}"},"title":"Qucik Response","progress":94,"progressColor":"var(--wp--preset--color--primary)","strokeColor":"rgba(217,217,217,1)","commonStyles":{"desktop":".eb-parent-eb-progressbar-362ez{display:block}.root-eb-progressbar-362ez{position:relative}","tab":".eb-parent-eb-progressbar-362ez{display:block}","mobile":".eb-parent-eb-progressbar-362ez{display:block}"}} -->
<div class="wp-block-essential-blocks-progress-bar  root-eb-progressbar-362ez"><div class="eb-parent-wrapper eb-parent-eb-progressbar-362ez "><div class="eb-progressbar-wrapper eb-progressbar-362ez"><div class="eb-progressbar-line-container center"><div class="eb-progressbar-title"><?php esc_html_e('Qucik Response','alpha-digital-agency'); ?></div><div class="eb-progressbar eb-progressbar-line" data-layout="line" data-count="94" data-duration="1500"><span class="eb-progressbar-count-wrap"><span class="eb-progressbar-count"><?php esc_html_e('94','alpha-digital-agency'); ?></span><span class="postfix">%</span></span><span class="eb-progressbar-line-fill"></span></div></div></div></div></div>
<!-- /wp:essential-blocks/progress-bar --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->